config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :users, except: [:new] do
    member do
      post 'activate'
      post 'deactivate'
    end
  end
  resources :resources
  resources :missing_people
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/resume', to: 'pages#resume'

  resources :form_fields, only: [:create, :update, :destroy]



  namespace :api do
    namespace :v1 do
      resources :users
      resources :missing_people
      resources :resources
      post 'login' => 'sessions#create'
      post 'logout' => 'sessions#destroy'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    enum tipo: [:Usuario, :Admin, :Invitado]
    enum perfil: [:Médico, :Enfermero, :TES, :Socorrista, :Humanitario, :Psicólogo, :Administrativo, :Mantenimiento]
    has_secure_password
    validates :password, presence: true, on: :create
    has_many :user_resources, dependent: :destroy
    has_many :resources, through: :user_resources
    validates :email, uniqueness: true
    validates :name, presence: true
    #validates :dni, presence: true, length: { is: 9 }

    def user_activation
        self.active = true
        self.save
    end

    def user_deactivation
        self.active = false
        self.save
    end

    def set_token
      self.auth_token = generate_token
      save
    end
  
    def generate_token
      loop do
        token = SecureRandom.hex(10)
        break token unless User.where(auth_token: token).exists?
      end
    end
end

app/controllers/api/v1/users_controller.rb
module Api::V1
    class UsersController < ApiController
        before_action :set_user, only: [:show, :destroy, :update]
        #before_action :req_token
        def index
            @users = User.all
        end

        def show
        end
        def create
            @user = User.new(user_params)
            
             if  @user.save
                render json: {message: "Usuario creado"}

            else
                render json: {message: "Error al crear usuario"}
            end
    
        end

        def update
            @user.update(user_params)
            head :no_content
        end

        def destroy
            @user.destroy
            head :no_content
        end

        def user_params
            params.permit(:name, :email, :password, :password_confirmation, :tipo, :active, :age, :perfil, :phone, :dni, resource_ids:[])
        end

        def set_user
            @user = User.find(params[:id])
        end

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :destroy, :update, :activate, :deactivate]
    before_action :require_admin, except: [:new, :create]
    def index
        @users = User.all.order(:name)
    end

    def new
        @user= User.new
    end
    
    def create
        @user= User.new(user_params)
        if @user.save
            flash[:success] = "Usuario creado!"
            redirect_to root_path
        else
            render 'new'
        end
    end

    def show
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:success] = "Se actualizaron los datos de usuario."
                redirect_to users_path
        else
            render 'edit'
    end

    end

    def destroy
        if !@user.admin?
        @user.destroy
        flash[:danger]="Usuario eliminado"
        redirect_to users_path
        end
    end

    def activate
        if @user.user_activation
        flash[:success] = "Usuario activado."
        redirect_to users_path
        else
            render 'index'
        end
    end
    def deactivate
       if  @user.user_deactivation
        flash[:success] = "Usuario activado."
        redirect_to users_path
        else
        render 'index'
       end
    end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :tipo, :active, :age, :perfil, :phone, :dni, resource_ids:[])
    end

    def set_user
        @user = User.find(params[:id])
    end

    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<script>
window.onmousedown = function (e) {
    var el = e.target;
    if (el.tagName.toLowerCase() == 'option' && el.parentNode.hasAttribute('multiple')) {
        e.preventDefault();

        // toggle selection
        if (el.hasAttribute('selected')) el.removeAttribute('selected');
        else el.setAttribute('selected', '');

        // hack to correct buggy behavior
        var select = el.parentNode.cloneNode(true);
        el.parentNode.parentNode.replaceChild(select, el.parentNode);
    }
}</script>
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="card mt-3">
        <div class="card-head bg-red">
            <h1 class="text-center my-2 text-white">
              <% if !@user.new_record? %>
                Editar Usuario
              <% else %>
                Nuevo Usuario
              <% end %>
            </h1>
        </div>
        <div class="card-body">
        <%= render 'shared/errors', obj: @user %>
          <%= form_for(@user, :html => {class: "", role: "form"}) do |f| %>
          <%= render 'layouts/messages' %>
          <div class="row">
            <div class="col-6">
               <div class="form-group">
              <div class="col-12 mx-auto">
                <%= f.text_field :name, class: "form-control",placeholder: "Nombre", autofocus: true, required: true%>
              </div>
          </div>

          <div class="form-group">
              <div class="col-12 mx-auto">
                <%= f.text_field :dni, class: "form-control",placeholder: "DNI", required: true%>
              </div>
          </div>

          <div class="form-group">
              <div class="col-12 mx-auto">
                <%= f.phone_field :phone, class: "form-control",placeholder: "Teléfono", required: true%>
              </div>
          </div>

          <div class="form-group">
              <div class="col-12 mx-auto">
                <%= f.number_field :age, class: "form-control",placeholder: "Edad", required: true%>
              </div>
          </div>
          <div class="form-group">
              <div class="col-12 mx-auto">
                  <%= f.email_field :email, class: "form-control", placeholder: "Correo electrónico", required: true %>
              </div>
          </div>
            </div>
            <div class="col-6">
          <% if @user.new_record? %>
            <div class="form-group">
                <div class="col-12 mx-auto">
                    <%= f.password_field :password, class: "form-control", placeholder: "Contraseña", required: true %>
                </div>
            </div>

            <div class="form-group">
                <div class="col-12 mx-auto">
                    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirmar contraseña", required: true %>
                </div>
            </div>
          <% end %>
          <!-- Para formulario de edit -->
          <% if !@user.new_record? %>
          <div class="form-group">
                <div class="col-12 mx-auto">
                    <%= f.password_field :password, class: "form-control", placeholder: "Contraseña" %>
                </div>
            </div>

            <div class="form-group">
                <div class="col-12 mx-auto">
                    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirmar contraseña" %>
                </div>
            </div>
            <div class="form-group">
              <div class="col-12 mx-auto">
                <%= f.select :tipo, User.tipos.keys.to_a,{}, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-12 mx-auto">
                <%= f.select :perfil, User.perfils.keys.to_a,{}, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-12 mx-auto">
              <%= f.select(:resource_ids, Resource.all.collect {|p| [ p.name, p.id ] },{},{ class: 'form-control', :multiple => true}) %>
              </div>
            </div>
          </div>
          <% end %>
          <!-- Fin de edit de usuario -->
            
          </div>

          
        <% end %>
    </div>
    <div class="card-footer">
      <div class="col-12">
        <div class="form-group mb-0">
            <div class="col-6 mx-auto text-center">
              <input type="submit" name="commit" value="Aceptar" class="btn btn-small btn-primary">
              <%= link_to 'Cancelar'.html_safe, '/users', class: "btn btn-small btn-danger" %>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="row bg-gardient-red mb-3">
    <div class="col-4">
    </div>
    <div class="col-4">
        <h1 class="mt-3 text-center text-white">Usuarios</h1>
    </div>
    <div class="col-4 text-right">
    <a href="/signup" class="mt-3 btn btn-small btn-light"><i class="material-icons align-middle">person_add</i>Nuevo</a>        
    </div>
</div>
<%= render 'layouts/messages' %>
<div class="row justify-content-center">
  <div class="col-12">
    <table id="dataTable" class="table table-striped table-hover display">
      <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">DNI</th>
            <th scope="col">Teléfono</th>
            <th scope="col">Perfil</th>
            <th scope="col">Correo</th>
            <th scope="col">Creación</th>
            <th scope="col">Tipo</th>
            <th scope="col" class="text-center">Estado</th>
            <th scope="col" class="text-center">Editar</th>
            <th scope="col" class="text-center">Borrar</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td scope="row"><%= user.id %></td>
            <td scope="row"><%= link_to user.name, user_path(user.id) %></td>
            <td scope="row"><%= user.dni %></td>
            <td scope="row"><%= user.phone %></td>
            <td scope="row"><%= user.perfil %></td>
            <td scope="row"><%= user.email.capitalize %></td>
            <td scope="row">
            <%= user.created_at.strftime('%d')+ '/' +user.created_at.strftime('%m')+ '/' +user.created_at.strftime('%Y')+ '  ' +user.created_at.strftime('%H')+ ':' +user.created_at.strftime('%M')+ ':' +user.created_at.strftime('%S')
            %>
            </td>
            <td scope="row"><%= user.tipo %></td>
            <td scope="row">
              <% if user.active? %>
                <% if current_user.name == user.name %>
                  <button class="btn btn-small btn-success ml-3 disabled"><i class="material-icons align-middle">power_settings_new</i></button>              
                <% else %>
                  <%= link_to '<i class="material-icons align-middle">power_settings_new</i>'.html_safe, deactivate_user_path(user) ,method: :post , class: "btn btn-small btn-success ml-3"%>
                <% end %>
              <% else %>
                <% if current_user.name == user.name %>
                  <button class="btn btn-small btn-outline-success ml-3 disabled"><i class="material-icons align-middle">power_settings_new</i></button>
                <% else %>
                  <%= link_to '<i class="material-icons align-middle">power_settings_new</i>'.html_safe,  activate_user_path(user) ,method: :post , class: "btn btn-small btn-outline-success ml-3"%>
                <% end %>
              <% end %>
            </td>
            <td scope="row">
              <%= link_to '<i class="material-icons align-middle">settings</i>'.html_safe, edit_user_path(user), class: "btn btn-small btn-primary ml-3"%>
            </td>
            <td scope="row">
              <% if current_user.name == user.name %>
                <button class="btn btn-small btn-dark ml-3 disabled"><i class="material-icons align-middle">delete</i></button>
              <% else %>
                <%= link_to '<i class="material-icons align-middle">delete</i>'.html_safe ,user_path(user), method: :delete, data: {confirm: "¿Desea eliminar el usuario "+user.name+"?"}, class: "btn btn-small btn-danger ml-3"%>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
$(document).ready( function () {
    $('#dataTable').DataTable({
        "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json"
            },
        dom: 'Bfrtip',
        buttons: [
            'copy', 
            'csv', 
            'excel',
            {
                extend: 'pdf',
                title: 'Usuarios',
                messageTop: 'Listado de usuarios con acceso al sistema.',
                exportOptions: {
                    columns: [ 0, 1, 2, 3, 4, 5, 6 ,7 ]
                },
            },
        ],
        
        "pagingType": "full_numbers",
        "order": [[ 0, "desc" ]],
        "columnDefs": [ {
          "targets": [8,9,10],
          "orderable": false
        } ]

    });
});
</script>

app/views/users/new.html.erb
<%= render 'form', obj: @user %>

app/views/users/show.html.erb
<%= render 'shared/page_title', title: "Perfil"  %>

<div class="row">
  <div class="col-12">
    <div class="card mx-auto" style="width: 30rem;">
      <div class="card-header">
        <h2 class="text-center"><%= @user.name %></h2>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>DNI: </strong><%= @user.dni %></li>
        <li class="list-group-item"><strong>Edad: </strong><%= @user.age %></li>
        <li class="list-group-item"><strong>Teléfono: </strong><%= @user.phone %></li>
        <li class="list-group-item"><strong>Email: </strong><%= @user.email %></li>
        <li class="list-group-item"><strong>Perfil: </strong><%= @user.perfil %></li>
        <li class="list-group-item"><strong>Estado: </strong>
        <% if @user.active %>
        <%= 'Activo' %>
        <% else %>
        <%= 'Inactivo' %>
        <% end %></li>
        <li class="list-group-item"><strong>Antiguedad: </strong>
            <%= @user.created_at.strftime('%d')+ '/' +@user.created_at.strftime('%m')+ '/' +@user.created_at.strftime('%Y') %>     
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-6">
              <strong>Recursos asignados:</strong>
            </div>
            <% @user.resources.each do |resource| %>
            <div class="col-3">
              
                <h4><span class="badge bg-red text-white w-100"><%= link_to resource.name, resource, class: "text-decoration-none text-reset" %></span></h4>
              
            </div>
            <% end %>
          </div> 
        </li>

      </ul>
      <div class="card-footer text-center">
      <%= link_to '<i class="material-icons align-middle">undo</i> Volver'.html_safe, :back, class: "btn btn-small btn-primary" %>
      </div>
    </div>
  </div>
</div>