config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :users, except: [:new] do
    member do
      post 'activate'
      post 'deactivate'
    end
  end
  resources :resources
  resources :missing_people
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/resume', to: 'pages#resume'

  resources :form_fields, only: [:create, :update, :destroy]



  namespace :api do
    namespace :v1 do
      resources :users
      resources :missing_people
      resources :resources
      post 'login' => 'sessions#create'
      post 'logout' => 'sessions#destroy'
    end
  end
end

app/views/resources/_form.html.erb
<%= render 'shared/errors', obj: @resource %>
<div class="row justify-content-center">
  <div class="col-5">
    <div class="card my-5">
      <div class="card-head bg-gardient-red">
        <h1 class="text-center my-2 text-white">
          <% if !@resource.new_record? %>
            Editar Recurso
          <% else %>
            Nuevo Recurso
          <% end %>
        </h1>
      </div>
      <%= form_for(@resource, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="card-body">
          <div class="row justify-content-center">
            <div class="col-8">
              <% if logged_in? && current_user.tipo != "Admin" %>
            <div class="form-group text-center">
              <label for="name">Nombre</label>
              <%= f.text_field :name, class: "form-control", id: "name", placeholder: "Introduce el nombre del recurso", autofocus: true, readonly: true %>
            </div>
            <div class="form-group text-center">
              <label for="localization">Localización</label>
              <%= f.text_field :localization, class: "form-control", id: "localization", placeholder: "Introduce localización", readonly: true%>
            </div>
            <div class="form-group text-center">
              <label for="category">Categoría</label>
              <%= f.select :category, Resource.categories.keys.to_a,{}, {class: 'form-control',  disabled: true } %>
            </div>
          <% else %>
            <div class="form-group text-center">
              <label for="name">Nombre</label>
              <%= f.text_field :name, class: "form-control", id: "name", placeholder: "Introduce el nombre del recurso", autofocus: true %>
            </div>
            <div class="form-group text-center">
              <label for="localization">Localización</label>
              <%= f.text_field :localization, class: "form-control", id: "localization", placeholder: "Introduce localización"%>
            </div>
            <div class="form-group text-center">
              <label for="category">Categoría</label>
              <%= f.select :category, Resource.categories.keys.to_a,{:prompt => 'Seleccionar'}, {class: 'form-control'} %>
            </div>
          <% end %>
            </div>
          </div>
          <!-- Para formulario de edit con el modal  -->
          <% if !@resource.new_record? && current_user.tipo == "Admin" %>
            <div class="row bg-gardient-red">
              <div class="col-3"></div>
              <div class="col-6">
                <h3 class="text-center text-white pt-2"><strong>Formulario</strong></h3>
              </div>
              <div class="col-3 text-center">
                <!-- BOTON DE ABRIR EL MODAL -->
                <button type="button" class="btn btn-small btn-light m-2" data-toggle="modal" data-target="#newfield"><i class="material-icons align-middle">playlist_add</i></button>
                </div>
            </div>
          <%= render 'layouts/messages' %>
          <% end %> 
          <div class="row justify-content-center">
            <div class="col-8 text-center py-4">
              <!-- Campos extra del formulario  -->
              <%= f.fields_for :form_fields do |form| %>
                <div class="form-group text-center">
                    <%= form.label :label, form.object.label %>
                  <div class="input-group mb-3">
                    <% if form.object.input_type == "Texto"%>
                      <%= form.text_field :value, class: "form-control" %>
                    <% end %>
                    <% if form.object.input_type == "Número"%>
                      <%= form.number_field :value, class: "form-control" %>
                    <% end %>
                    <% if form.object.input_type == "Descripción"%>
                      <%= form.text_area :value, class: "form-control", rows: "5", maxlength: 255 %>
                    <% end %>
                    <% if logged_in? && current_user.tipo == "Admin" %>
                      <div class="input-group-append">
                        <%= link_to form_field_path(form.object.id), method: :delete, data: { confirm: "¿Desea eliminar el campo "+form.object.label+"?" }, title: 'Eliminar campo' do %>
                        <i class="material-icons align-middle text-danger">close</i>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
              <!-- Fin de campos extra de formulario  -->
            </div>
          </div>
        </div>
        <div class="card-footer">
            <div class="text-center">
               <%= f.submit "Aceptar", class: "btn btn-small btn-primary" %>
              <%= link_to 'Cancelar'.html_safe, :back, class: "btn btn-small btn-danger" %>            
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- MODAL DE AÑADIR CAMPO NUEVO -->
<div class="modal fade" id="newfield" role="dialog">
  <div class="modal-dialog edit-news">
    <div class="modal-content">
      <div class="modal-header bg-gardient-red">
        <div class="col-3"></div>
        <div class="col-6">
          <h3 class="modal-title text-center text-white pt-2"><strong>Añadir campo</strong></h3>
        </div>
        <div class="col-3 text-center">
          <button type="button" class="close m-0" data-dismiss="modal" aria-label="Close"><i class="material-icons align-middle text-white">close</i></button>
        </div>
      </div>
      <div class="modal-body">
          <% @new_field = FormField.new %>
          <%= form_for @new_field, html: {class: 'form-horizontal'} do |f| %>
            <%= render 'modal_field_form', f: f %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/resources/_modal_field_form.html.erb
<div class="nested-fields">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="form-group">
        <%= f.label :label, "Nombre del campo" %>
        <%= f.text_field :label, class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= f.label :input_type, "Tipo de campo" %>
        <%= f.select :input_type, FormField.input_types.keys.to_a,{}, class: "form-control" %>
      </div>
      <div align="center">
        <%= f.hidden_field :resource_id, :value => @resource.id %>
        <%= f.submit("Añadir" ,class: "btn btn-primary btn-small") %>
      </div>
    </div>
  </div>
</div>

app/views/resources/edit.html.erb
<%= render 'form' %>

app/views/resources/index.html.erb
<div class="row bg-gardient-red mb-3">
    <div class="col-4">
    </div>
    <div class="col-4">
        <h1 class="mt-3 text-center text-white">Recursos</h1>
    </div>
    <div class="col-4 text-right">
    <a href="/resources/new" class="mt-3 btn btn-small btn-light"><i class="material-icons align-middle">person_add</i>Nuevo</a>        
    </div>
</div>
<%= render 'layouts/messages' %>
<% if @resources.count == 0%>
<div class="row">
  <div class="col-12">
    <h1 class="display-4 text-center">No hay recursos creados</h1>
  </div>
</div>
<% end %>
<% if @resources_filter.count == 0 && current_user.tipo != "Admin"%>
<div class="row">
  <div class="col-12">
    <h1 class="display-4 text-center">No tienes recursos asignados</h1>
  </div>
</div>
<% end %>
<div class="card-deck">
<% if logged_in? && current_user.tipo == "Admin" %>
  <% @resources.each do |resource| %>
    <div class="col-12 col-md-6 col-lg-4 d-flex align-items-stretch">
      <div class="card mb-3 shadow">
        <div class="card-body text-center">
          <strong><%= link_to resource.name.capitalize, resource_path(resource), class: "h2 card-title text-reset " %></strong>
          <div class="row justify-content-center">
            <div class="col-5 text-left my-3">
              <span class="card-text text-center"><strong>Categoría:</strong></span><br/>
              <span class="card-text text-center"><strong>Localización:</strong></span>
              <span class="card-text text-center"><strong>Dotación:</strong></span>
            </div>
            <div class="col-4 text-left my-3">
              <%= resource.category %><br/>
              <%= resource.localization %><br/>
              <%= resource.users.count %>
            </div>
            <div class="row">
              <div class="col-12">
                <% if resource.form_fields.count == 0%>
                  <h4><span class="badge bg-red text-white">Sin Formulario</span></h4>
                <% else %>
                  <h4><span class="badge badge-success">Formulario Creado</span></h4>  
                <% end %>
              </div>
            </div>
          </div>
          <%= link_to '<i class="material-icons align-middle">settings</i>Editar'.html_safe, edit_resource_path(resource), class: "btn btn-small btn-primary mt-2"%>
          <%= link_to '<i class="material-icons align-middle">delete</i>Borrar'.html_safe, resource_path(resource), method: :delete,class: "btn btn-small btn-danger mt-2",data: {confirm: '¿Está seguro de eliminar el recurso ' +resource.name+ '?'}%>
        </div>
        <div class="card-footer text-center">
          <small class="text-muted">Creado <%= resource.created_at %></small>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <% @resources_filter.each do |resource| %>
    <div class="col-12 col-md-6 col-lg-4 d-flex align-items-stretch">
      <div class="card mb-3">
        <div class="card-body text-center">
          <%= link_to resource.name.capitalize, resource_path(resource), class: "h2 card-title" %>
          <div class="row justify-content-center">
            <div class="col-5 text-left my-3">
              <span class="card-text text-center"><strong>Categoría:</strong></span><br/>
              <span class="card-text text-center"><strong>Localización:</strong></span>
              <span class="card-text text-center"><strong>Dotación:</strong></span>
            </div>
            <div class="col-4 text-left my-3">
              <%= resource.category %><br/>
              <%= resource.localization %><br/>
              <%= resource.users.count %>
            </div>
          </div>
          <%= link_to '<i class="material-icons align-middle">settings</i>Formulario'.html_safe, edit_resource_path(resource), class: "btn btn-small btn-primary"%>
        </div>
        <div class="card-footer text-center">
          <small class="text-muted">Creado <%= resource.created_at %></small>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

</div>

app/views/resources/new.html.erb
<%= render 'form', obj: @resource %>

app/views/resources/show.html.erb
<%= render 'shared/page_title', title: "Detalles del Recurso"  %>

<div class="row justify-content-around">
  <div class="col-3">
    <div class="card mx-auto">
      <div class="card-header">
        <div class="row">
          <div class="col-8">
            <h2 class="text-right mt-2"><%= @resource.name %></h2>
          </div>
          <div class="col-4">
            <%= link_to '<i class="material-icons align-middle">settings</i>'.html_safe, edit_resource_path(@resource), class: "btn btn-small bg-gardient-red text-light mt-2"%>
          </div>
        </div>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Categoria: </strong><%= @resource.category %></li>
        <li class="list-group-item"><strong>Localización: </strong><%= @resource.localization %></li>
        <li class="list-group-item"><strong>Dotación asignada: </strong><%= @resource.users.count %></li>
        <li class="list-group-item"><strong>Campos de formulario: </strong><%= @resource.form_fields.count %></li>
        <li class="list-group-item"><strong>Creación: </strong>
            <%= @resource.created_at.strftime('%d')+ '/' +@resource.created_at.strftime('%m')+ '/' +@resource.created_at.strftime('%Y') %>     
        </li>
      </ul>
      <div class="card-footer text-center">
      <%= link_to '<i class="material-icons align-middle">undo</i> Volver'.html_safe, :back, class: "btn btn-small btn-primary" %>
      </div>
    </div>
  </div>
  <div class="col-8">
   <table id="dataTable" class="table table-striped table-hover display">
      <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Teléfono</th>
            <th scope="col">Perfil</th>
            <th scope="col">Correo</th>
            <th scope="col">Tipo</th>
        </tr>
      </thead>
      <tbody>
        <% @resource.users.each do |user| %>
          <tr>
            <td scope="row"><%= user.id %></td>
            <td scope="row"><%= link_to user.name, user_path(user.id) %></td>
            <td scope="row"><%= user.phone %></td>
            <td scope="row"><%= user.perfil %></td>
            <td scope="row"><%= user.email.capitalize %></td>
            <td scope="row"><%= user.tipo %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
$(document).ready( function () {
    $('#dataTable').DataTable({
        "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json"
            },
        dom: 'Bfrtip',
        buttons: [
            'copy', 
            'csv', 
            'excel',
            {
                extend: 'pdf',
                title: 'Usuario asignados a <%= @resource.name%>',
            },
        ],
        
        "pagingType": "full_numbers",
        "order": [[ 0, "desc" ]],

    });
});
</script>