config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :users, except: [:new] do
    member do
      post 'activate'
      post 'deactivate'
    end
  end
  resources :resources
  resources :missing_people
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/resume', to: 'pages#resume'

  resources :form_fields, only: [:create, :update, :destroy]



  namespace :api do
    namespace :v1 do
      resources :users
      resources :missing_people
      resources :resources
      post 'login' => 'sessions#create'
      post 'logout' => 'sessions#destroy'
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="row bg-red align-center py-2 mt-5">
    <div class="col-12 text-center">
    <p class="text-white">Desarrollado por <strong>Wycorp</strong></p>
    </div>
</footer>
<!-- Footer -->

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-8 mx-auto">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav id="nav" class="row navbar navbar-expand-lg navbar-light bg-light align-center">
  <a href="/"><%= image_tag 'logo.svg', class: "d-inline-block align-top mx-5" %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <% if logged_in? && current_user.tipo == 'Admin'%>
        <li class="nav-item">
          <%= link_to "Resumen", resume_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Recursos", resources_path, class: "nav-link" %>
      </li>
      <% if logged_in? && current_user.tipo == 'Admin'%>
        <li class="nav-item">
          <%= link_to "Usuarios", users_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Desaparecidos", missing_people_path, class: "nav-link" %>
      </li>
    </ul>
    <!-- Right Side Of Navbar -->
    <ul class="navbar-nav text-center ml-auto mt-2">
      <li class="nav-item dropdown">
        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown">
          <%= current_user.name.capitalize %> 
          <span class="caret"></span>
        </a>

        <div class="dropdown-menu dropdown-menu-right">
          <ul class="list-group">
            <li class="list-group-item">
              <%= link_to "Perfil",user_path(current_user), class: "text-reset"%>
            </li>
            <li class="list-group-item">
              <%= link_to "Salir", logout_path,method: :delete, class: "text-reset" %>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'icon.png'%>
    <%= stylesheet_link_tag    'styles'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- DataTable Bootstrap -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <!-- Material Icons CSS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- DataTable -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <!-- Buttons DataTable -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css">
  </head>

  <body class="">
      <% if logged_in? %>
        <div class="container-fluid d-flex flex-column vh-100 justify-content-between">
        <%= render 'layouts/navigation' %>

        <%= yield %>

        <%= render 'layouts/footer' %>
        </div>
      <% else %>

        <%= yield %>

      <% end %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- DataTable JS -->
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <!-- Buttons DataTable JS -->
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    
  </body>
</html>